runtime: python39  # Specify the Python runtime

entrypoint: gunicorn -b :$PORT app:app  # Use Gunicorn to run your Flask app

# Ensure the static directory is correctly mapped
handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

# Optional: Environment variables
env_variables:
  FLASK_ENV: 'production'
