steps:
  # App Engine deploy step 1
  - name: 'python:3.9-slim'
    id: 'Install dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt

  # App Engine deploy step 2
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to App Engine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy app.yaml --quiet

  # Cloud Run build and deploy steps
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cot5390-project1:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cot5390-project1:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'cot5390-project1'
    - '--image'
    - 'gcr.io/$PROJECT_ID/cot5390-project1:$COMMIT_SHA'
    - '--region'
    - 'SERVICE_REGION'
images:
- 'gcr.io/$PROJECT_ID/cot5390-project1:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY