steps:
  # Install dependencies
  - name: 'python:3.9-slim'
    id: 'Install dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt

  # Deploy to Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to App Engine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy app.yaml --quiet

    # Step 1: Build the container image using Cloud Buildpacks
  - name: 'gcr.io/buildpacks/builder:v1'
    args:
      - '--tag=gcr.io/cot-5930-course-project-441622/app'

    # Step 2: Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'app'         # Change `my-flask-app` to your Cloud Run service name
      - '--image=gcr.io/cot-5930-course-project-441622/app' # Reference the image built in Step 1
      - '--platform=managed'
      - '--region=us-central1'                  # Set your preferred region
      - '--allow-unauthenticated'                  # Optional: Allow public access

options:
  logging: CLOUD_LOGGING_ONLY