steps:
  # Step 1: Install dependencies
  - name: 'python:3.9'
    id: 'Install dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt

  # Step 2: Deploy to Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to App Engine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy app.yaml --quiet

# Optional: Timeout setting if the build takes a while
timeout: '900s'  # 15 minutes timeout (adjust as necessary)

options:
  logging: CLOUD_LOGGING_ONLY
