steps:
  # App Engine deploy step 1
  - name: 'python:3.9-slim'
    id: 'Install dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt

  # App Engine deploy step 2
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to App Engine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy app.yaml --quiet

  # Cloud Run build and deploy steps
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cot-5930-course-project-441622/app', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cot-5930-course-project-441622/app']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'cot5390-project1', '--image', 'gcr.io/cot-5930-course-project-441622/app', '--region', 'us-west1']
images:
- gcr.io/cot-5930-course-project-441622/app

options:
  logging: CLOUD_LOGGING_ONLY